name: publishing

on:
  push:
    tags: '*'

jobs:
  app-config:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: yarn install

    - name: app-config-config
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-config/package.json
    - name: app-config-core
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-core/package.json
    - name: app-config-cypress
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-cypress/package.json
    - name: app-config-electron
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-electron/package.json
    - name: app-config-default-extensions
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-default-extensions/package.json
    - name: app-config-encryption
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-encryption/package.json
    - name: app-config-exec
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-exec/package.json
    - name: app-config-extension-utils
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-extension-utils/package.json
    - name: app-config-extensions
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-extensions/package.json
    - name: app-config-generate
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-generate/package.json
    - name: app-config-git
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-git/package.json
    - name: app-config-inject
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-inject/package.json
    - name: app-config-js
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-js/package.json
    - name: app-config-logging
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-logging/package.json
    - name: app-config-meta
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-meta/package.json
    - name: app-config-node
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-node/package.json
    - name: app-config-react-native
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-react-native/package.json
    - name: app-config-schema
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-schema/package.json
    - name: app-config-settings
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-settings/package.json
    - name: app-config-utils
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-utils/package.json
    - name: app-config-v1-compat
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-v1-compat/package.json
    - name: app-config-vault
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-vault/package.json
    - name: app-config-webpack
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-webpack/package.json
    - name: app-config-rollup
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-rollup/package.json
    - name: app-config-vite
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-vite/package.json
    - name: lcdev-app-config-inject
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./lcdev-app-config-inject/package.json
    - name: lcdev-app-config-webpack-plugin
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./lcdev-app-config-webpack-plugin/package.json
    - name: lcdev-react-native-app-config-transformer
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./lcdev-react-native-app-config-transformer/package.json

    # Do these last, since they're most commonly used by consumers
    - name: app-config-cli
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-cli/package.json
    - name: app-config-main
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./app-config-main/package.json
    - name: lcdev-app-config
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./lcdev-app-config/package.json
